/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProgramlistRouteImport } from './routes/programlist'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAssigningRouteImport } from './routes/admin.assigning'
import { Route as AdminControlRouteImport } from './routes/admin.control'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminProgrammesRouteImport } from './routes/admin.programmes'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamAnnouncementsRouteImport } from './routes/team.announcements'
import { Route as TeamAssignRouteImport } from './routes/team.assign'
import { Route as TeamOverviewRouteImport } from './routes/team.overview'
import { Route as TeamStudentsRouteImport } from './routes/team.students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramlistRoute = ProgramlistRouteImport.update({
  id: '/programlist',
  path: '/programlist',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssigningRoute = AdminAssigningRouteImport.update({
  id: '/assigning',
  path: '/assigning',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControlRoute = AdminControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgrammesRoute = AdminProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRoute,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamAnnouncementsRoute = TeamAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => TeamRoute,
} as any)
const TeamAssignRoute = TeamAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => TeamRoute,
} as any)
const TeamOverviewRoute = TeamOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => TeamRoute,
} as any)
const TeamStudentsRoute = TeamStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/documents': typeof DocumentsRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/programlist': typeof ProgramlistRoute
  '/registration': typeof RegistrationRoute
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRouteWithChildren
  '/teams': typeof TeamsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assigning': typeof AdminAssigningRoute
  '/admin/control': typeof AdminControlRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/team/announcements': typeof TeamAnnouncementsRoute
  '/team/assign': typeof TeamAssignRoute
  '/team/overview': typeof TeamOverviewRoute
  '/team/students': typeof TeamStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/documents': typeof DocumentsRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/programlist': typeof ProgramlistRoute
  '/registration': typeof RegistrationRoute
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assigning': typeof AdminAssigningRoute
  '/admin/control': typeof AdminControlRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/team/announcements': typeof TeamAnnouncementsRoute
  '/team/assign': typeof TeamAssignRoute
  '/team/overview': typeof TeamOverviewRoute
  '/team/students': typeof TeamStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/team': typeof TeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/documents': typeof DocumentsRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/programlist': typeof ProgramlistRoute
  '/registration': typeof RegistrationRoute
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRouteWithChildren
  '/teams': typeof TeamsRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assigning': typeof AdminAssigningRoute
  '/admin/control': typeof AdminControlRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/programmes': typeof AdminProgrammesRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/team/announcements': typeof TeamAnnouncementsRoute
  '/team/assign': typeof TeamAssignRoute
  '/team/overview': typeof TeamOverviewRoute
  '/team/students': typeof TeamStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/certificate'
    | '/documents'
    | '/gallery'
    | '/live'
    | '/login'
    | '/programlist'
    | '/registration'
    | '/results'
    | '/schedule'
    | '/settings'
    | '/team'
    | '/teams'
    | '/admin/accounts'
    | '/admin/announcements'
    | '/admin/assigning'
    | '/admin/control'
    | '/admin/overview'
    | '/admin/programmes'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/timetable'
    | '/team/announcements'
    | '/team/assign'
    | '/team/overview'
    | '/team/students'
    | '/admin/'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/documents'
    | '/gallery'
    | '/live'
    | '/login'
    | '/programlist'
    | '/registration'
    | '/results'
    | '/schedule'
    | '/settings'
    | '/teams'
    | '/admin/accounts'
    | '/admin/announcements'
    | '/admin/assigning'
    | '/admin/control'
    | '/admin/overview'
    | '/admin/programmes'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/timetable'
    | '/team/announcements'
    | '/team/assign'
    | '/team/overview'
    | '/team/students'
    | '/admin'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/certificate'
    | '/documents'
    | '/gallery'
    | '/live'
    | '/login'
    | '/programlist'
    | '/registration'
    | '/results'
    | '/schedule'
    | '/settings'
    | '/team'
    | '/teams'
    | '/admin/accounts'
    | '/admin/announcements'
    | '/admin/assigning'
    | '/admin/control'
    | '/admin/overview'
    | '/admin/programmes'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/timetable'
    | '/team/announcements'
    | '/team/assign'
    | '/team/overview'
    | '/team/students'
    | '/admin/'
    | '/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CertificateRoute: typeof CertificateRoute
  DocumentsRoute: typeof DocumentsRoute
  GalleryRoute: typeof GalleryRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  ProgramlistRoute: typeof ProgramlistRoute
  RegistrationRoute: typeof RegistrationRoute
  ResultsRoute: typeof ResultsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRouteWithChildren
  TeamsRoute: typeof TeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programlist': {
      id: '/programlist'
      path: '/programlist'
      fullPath: '/programlist'
      preLoaderRoute: typeof ProgramlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assigning': {
      id: '/admin/assigning'
      path: '/assigning'
      fullPath: '/admin/assigning'
      preLoaderRoute: typeof AdminAssigningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/control': {
      id: '/admin/control'
      path: '/control'
      fullPath: '/admin/control'
      preLoaderRoute: typeof AdminControlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programmes': {
      id: '/admin/programmes'
      path: '/programmes'
      fullPath: '/admin/programmes'
      preLoaderRoute: typeof AdminProgrammesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/announcements': {
      id: '/team/announcements'
      path: '/announcements'
      fullPath: '/team/announcements'
      preLoaderRoute: typeof TeamAnnouncementsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/assign': {
      id: '/team/assign'
      path: '/assign'
      fullPath: '/team/assign'
      preLoaderRoute: typeof TeamAssignRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/overview': {
      id: '/team/overview'
      path: '/overview'
      fullPath: '/team/overview'
      preLoaderRoute: typeof TeamOverviewRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/students': {
      id: '/team/students'
      path: '/students'
      fullPath: '/team/students'
      preLoaderRoute: typeof TeamStudentsRouteImport
      parentRoute: typeof TeamRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAssigningRoute: typeof AdminAssigningRoute
  AdminControlRoute: typeof AdminControlRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminProgrammesRoute: typeof AdminProgrammesRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAssigningRoute: AdminAssigningRoute,
  AdminControlRoute: AdminControlRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminProgrammesRoute: AdminProgrammesRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TeamRouteChildren {
  TeamAnnouncementsRoute: typeof TeamAnnouncementsRoute
  TeamAssignRoute: typeof TeamAssignRoute
  TeamOverviewRoute: typeof TeamOverviewRoute
  TeamStudentsRoute: typeof TeamStudentsRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamAnnouncementsRoute: TeamAnnouncementsRoute,
  TeamAssignRoute: TeamAssignRoute,
  TeamOverviewRoute: TeamOverviewRoute,
  TeamStudentsRoute: TeamStudentsRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CertificateRoute: CertificateRoute,
  DocumentsRoute: DocumentsRoute,
  GalleryRoute: GalleryRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  ProgramlistRoute: ProgramlistRoute,
  RegistrationRoute: RegistrationRoute,
  ResultsRoute: ResultsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRouteWithChildren,
  TeamsRoute: TeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
